site_name: "hyrrokkin documentation"

theme:
  name: "readthedocs"
    #  name: "material"

markdown_extensions:
  - pymdownx.snippets:
      restrict_base_path: false
      check_paths: true

plugins:
  - mkdocstrings
docs_dir: docs

site_dir: ../docs

# mkdocis installation:
# pip install mkdocs
# python -m pip install "mkdocstrings[python]"
# python -m pip install mkdocs-material

